name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: 2. Setup Pages (Configuração do Ambiente)
        uses: actions/configure-pages@v5
        
      - name: 3. Upload dos Arquivos (Criar o Artefato)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './' 
          
      - name: 4. Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
